using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace CargoSpace.SourceGenerators;

[Generator]
public class GuidIdGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(EmitAttribute);

        var targets = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => TryGetGuidIdTarget(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(targets, static (spc, source) => Execute(spc, source));
    }

    private static void EmitAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("GuidIdAttribute.g.cs", SourceText.From(EmbeddedAttributeSource, Encoding.UTF8));
    }

    private static string EmbeddedAttributeSource
    {
        get
        {
            var assembly = typeof(GuidIdGenerator).GetTypeInfo().Assembly;
            var resourceName = assembly.GetManifestResourceNames()
                .FirstOrDefault(n => n.EndsWith("GuidIdAttribute.cs", StringComparison.Ordinal));

            if (resourceName is null)
            {
                throw new InvalidOperationException("GuidIdAttribute.cs embedded resource not found.");
            }

            using var stream = assembly.GetManifestResourceStream(resourceName);
            if (stream is null)
            {
                throw new InvalidOperationException($"Could not load embedded resource '{resourceName}'.");
            }

            using var reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }
    }

    private static TypeDeclarationSyntax TryGetGuidIdTarget(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;

        // Only struct or record struct; ignore classes, interfaces, record classes, etc.
        if (typeDeclaration is not StructDeclarationSyntax &&
            (typeDeclaration is not RecordDeclarationSyntax rds || rds.Kind() != SyntaxKind.RecordStructDeclaration))
        {
            return null;
        }

        foreach (var attributeList in typeDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name is "GuidId" or "GuidIdAttribute")
                {
                    return typeDeclaration;
                }
            }
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, TypeDeclarationSyntax target)
    {
        string typeName = target.Identifier.Text;

        var attribute = target.AttributeLists
            .SelectMany(a => a.Attributes)
            .FirstOrDefault(a =>
            {
                var name = a.Name.ToString();
                return name is "GuidId" or "GuidIdAttribute";
            });

        if (attribute is null)
        {
            return;
        }

        var prefix = attribute.ArgumentList?.Arguments
            .FirstOrDefault()?.Expression?.ToString()?.Trim('"') ?? "UNK";

        var source = new StringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine("using System;")
            .AppendLine()
            .AppendLine("namespace CargoSpace.Core;")
            .AppendLine()
            .AppendLine($"public readonly partial record struct {typeName}")
            .AppendLine("{")
            .AppendLine("    private readonly Guid _id;")
            .AppendLine($"    private const string Prefix = \"{prefix}\";")
            .AppendLine()
            .AppendLine($"    private {typeName}(Guid id) => _id = id;")
            .AppendLine()
            .AppendLine($"    public static {typeName} Create() => new {typeName}(Guid.NewGuid());")
            .AppendLine($"    public static {typeName} FromBytes(byte[] bytes) => new {typeName}(new Guid(bytes));")
            .AppendLine()
            .AppendLine("    public Guid GetGuid() => _id;")
            .AppendLine("    public byte[] ToNetworkBytes() => _id.ToByteArray();")
            .AppendLine()
            .AppendLine("    public override string ToString()")
            .AppendLine("    {")
            .AppendLine("        string shortId = Convert.ToBase64String(_id.ToByteArray()).TrimEnd('=');")
            .AppendLine($"        return $\"{{Prefix}}-{{shortId}}\";")
            .AppendLine("    }")
            .AppendLine("}")
            .ToString();

        context.AddSource($"{typeName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
