<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>CargoSpace</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Client\" />
    <Folder Include="Core\" />
    <Folder Include="Server\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Data\tiles.json" />
    <Content Include="Data\items.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CargoSpace.SourceGenerators\CargoSpace.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>